CREATE TYPE DmsType AS ENUM ('BASIC', 'COMPREHENSIVE','MAXIMUM');
CREATE TYPE InsuranceStatus AS ENUM ('PENDING','APPROVED','CANCELLED','REJECTED','ISSUED');
CREATE TYPE PaymentFrequency AS ENUM ('ONCE_IN_MONTH','ONCE_IN_THREE_MONTHS','ONCE_IN_SIX_MONTHS','ONCE_IN_TWELVE_MONTHS');
CREATE TYPE PaymentStatus AS ENUM ('PAID','PENDING','FAILED');
